In [30]:
!pip3 install openpyxl

Requirement already satisfied: openpyxl in /opt/conda/lib/python3.10/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /opt/conda/lib/python3.10/site-packages (from openpyxl) (1.1.0)

In [31]:
import pandas as pd
import openpyxl as oxl
import numpy as np

In [32]:
domain_helpers = pd.read_excel('/kaggle/input/hack2skill-assessment-data/Data Management Task.xlsx', sheet_name="Domain Helpers")

In [33]:
domain_helpers

,Name,Email,College Name,Contact Number,City,Gender
0,John Doe,johndoe@example.com,University A,123-456-7890,City X,Male
1,Ella Johnson,ellajohnson@example.com,University A,123-456-7890,City X,Female
2,Jane Smith,janesmith@example.com,College B,987-654-3210,City Y,Female
3,Evan Davis,evandavis@example.com,College B,987-654-3210,City Y,Male
4,Michael Johnson,michaeljohnson@example.com,Institute C,567-890-1234,City Z,Male
5,Sophia Wilson,sophiawilson@example.com,Institute C,567-890-1234,City Z,Female
6,Lucas Smith,lucassmith@example.com,University D,234-567-8901,City X,Male
7,Avery White,averywhite@example.com,College E,876-543-2109,City Y,Female
8,Owen Miller,owenmiller@example.com,Institute F,345-678-9012,City Z,Male
9,Aria Clark,ariaclark@example.com,University G,654-321-0987,City X,Female
10,Leo Brown,leobrown@example.com,College H,210-987-6543,City Y,Male
11,Mia Hall,miahall@example.com,Institute I,789-012-3456,City Z,Female
12,Isaac Taylor,isaactaylor@example.com,University J,432-109-8765,City X,Male
13,Layla Moore,laylamoore@example.com,College K,321-098-7654,City Y,Female
14,Carter Anderson,carteranderson@example.com,Institute L,901-234-5678,City Z,Male
15,Nova Walker,novawalker@example.com,University M,543-210-9876,City X,Female
16,Elijah Wilson,elijahwilson@example.com,College N,876-543-2109,City Y,Male
17,Zara Martinez,zaramartinez@example.com,Institute O,345-678-9012,City Z,Female
18,Henry Garcia,henrygarcia@example.com,University P,654-321-0987,City X,Male
19,Scarlett Davis,scarlettdavis@example.com,College Q,210-987-6543,City Y,Female
20,Gabriel Harris,gabrielharris@example.com,Institute R,789-012-3456,City Z,Male
21,Amelia Jackson,ameliajackson@example.com,University S,432-109-8765,City X,Female
22,Logan Brown,loganbrown@example.com,College T,321-098-7654,City Y,Male
23,Aurora Taylor,aurorataylor@example.com,Institute U,901-234-5678,City Z,Female
24,Jackie Lee,jackielee@example.com,University V,543-210-9876,City X,Male
25,Nora Wilson,norawilson@example.com,College W,876-543-2109,City Y,Female
26,Isaiah Miller,isaiahmiller@example.com,Institute X,345-678-9012,City Z,Male
27,Stella Hall,stellahall@example.com,University Y,654-321-0987,City X,Female
28,Caleb Anderson,calebanderson@example.com,College Z,210-987-6543,City Y,Male
29,Hazel Thomas,hazelthomas@example.com,Institute AA,789-012-3456,City Z,Female
30,Dylan Martin,dylanmartin@example.com,University BB,432-109-8765,City X,Male
31,Sophie Johnson,sophiejohnson@example.com,College CC,321-098-7654,City Y,Female

In [34]:
feedbacks = pd.read_excel('/kaggle/input/hack2skill-assessment-data/Data Management Task.xlsx', sheet_name="Feedbacks")

In [35]:
feedbacks.head()

,Timestamp,Email Address,Full Name,Registered Email ID,College Name,Rate your experience with the overall event,Rate the activity-1,Rate the following activity-2,Rate the following activity-3,Rate the following activity-4
0,2024-01-31 08:30:00,johndoe@example.com,John Doe,johndoe@example.com,University A,5,4,5,3,5
1,2024-01-31 09:15:00,ellajohnson@example.com,Ella Johnson,ellajohnson@example.com,University A,4,5,3,4,4
2,2024-01-31 10:00:00,janesmith@example.com,Jane Smith,janesmith@example.com,College B,4,4,4,5,4
3,2024-01-31 10:45:00,evandavis@example.com,Evan Davis,evandavis@example.com,College B,3,3,4,5,3
4,2024-01-31 11:30:00,michaeljohnson@example.com,Michael Johnson,michaeljohnson@example.com,Institute C,5,5,5,5,5

# Q.1 Filtering feedbacks of only Domain Leaders

In [36]:
domain_helpers_email = set(domain_helpers['Email'].unique())
domain_helpers_email

{'ameliajackson@example.com',
 'ariaclark@example.com',
 'aurorataylor@example.com',
 'averywhite@example.com',
 'calebanderson@example.com',
 'carteranderson@example.com',
 'dylanmartin@example.com',
 'elijahwilson@example.com',
 'ellajohnson@example.com',
 'evandavis@example.com',
 'gabrielharris@example.com',
 'hazelthomas@example.com',
 'henrygarcia@example.com',
 'isaactaylor@example.com',
 'isaiahmiller@example.com',
 'jackielee@example.com',
 'janesmith@example.com',
 'johndoe@example.com',
 'laylamoore@example.com',
 'leobrown@example.com',
 'loganbrown@example.com',
 'lucassmith@example.com',
 'miahall@example.com',
 'michaeljohnson@example.com',
 'norawilson@example.com',
 'novawalker@example.com',
 'owenmiller@example.com',
 'scarlettdavis@example.com',
 'sophiawilson@example.com',
 'sophiejohnson@example.com',
 'stellahall@example.com',
 'zaramartinez@example.com'}

In [37]:
domain_helpers_only_feedbacks = feedbacks[feedbacks['Registered Email ID'].isin(domain_helpers_email)].drop_duplicates()

In [38]:
domain_helpers_only_feedbacks

,Timestamp,Email Address,Full Name,Registered Email ID,College Name,Rate your experience with the overall event,Rate the activity-1,Rate the following activity-2,Rate the following activity-3,Rate the following activity-4
0,2024-01-31 08:30:00,johndoe@example.com,John Doe,johndoe@example.com,University A,5,4,5,3,5
1,2024-01-31 09:15:00,ellajohnson@example.com,Ella Johnson,ellajohnson@example.com,University A,4,5,3,4,4
2,2024-01-31 10:00:00,janesmith@example.com,Jane Smith,janesmith@example.com,College B,4,4,4,5,4
3,2024-01-31 10:45:00,evandavis@example.com,Evan Davis,evandavis@example.com,College B,3,3,4,5,3
4,2024-01-31 11:30:00,michaeljohnson@example.com,Michael Johnson,michaeljohnson@example.com,Institute C,5,5,5,5,5
5,2024-01-31 12:15:00,sophiawilson@example.com,Sophia Wilson,sophiawilson@example.com,Institute C,4,3,5,4,4
6,2024-01-31 13:00:00,lucassmith@example.com,Lucas Smith,lucassmith@example.com,University D,5,4,5,4,5
7,2024-01-31 13:45:00,averywhite@example.com,Avery White,averywhite@example.com,College E,3,5,4,3,3
8,2024-01-31 14:30:00,owenmiller@example.com,Owen Miller,owenmiller@example.com,Institute F,4,4,3,5,4
9,2024-01-31 15:15:00,ariaclark@example.com,Aria Clark,ariaclark@example.com,University G,5,5,4,5,5
10,2024-01-31 16:00:00,leobrown@example.com,Leo Brown,leobrown@example.com,College H,4,3,5,4,4
11,2024-01-31 16:45:00,miahall@example.com,Mia Hall,miahall@example.com,Institute I,5,4,4,5,5
12,2024-01-31 17:30:00,isaactaylor@example.com,Isaac Taylor,isaactaylor@example.com,University J,3,5,3,4,3
13,2024-01-31 18:15:00,laylamoore@example.com,Layla Moore,laylamoore@example.com,College K,4,4,5,5,4
14,2024-01-31 19:00:00,carteranderson@example.com,Carter Anderson,carteranderson@example.com,Institute L,5,3,4,5,5
15,2024-01-31 19:45:00,novawalker@example.com,Nova Walker,novawalker@example.com,University M,4,4,5,3,4
16,2024-01-31 20:30:00,elijahwilson@example.com,Elijah Wilson,elijahwilson@example.com,College N,5,5,4,4,5
17,2024-01-31 21:15:00,zaramartinez@example.com,Zara Martinez,zaramartinez@example.com,Institute O,3,4,5,5,3
18,2024-01-31 22:00:00,henrygarcia@example.com,Henry Garcia,henrygarcia@example.com,University P,5,3,4,5,5
19,2024-01-31 22:45:00,scarlettdavis@example.com,Scarlett Davis,scarlettdavis@example.com,College Q,4,5,5,4,4
20,2024-01-31 23:30:00,gabrielharris@example.com,Gabriel Harris,gabrielharris@example.com,Institute R,3,4,4,5,3
22,2024-02-01 01:00:00,loganbrown@example.com,Logan Brown,loganbrown@example.com,College T,4,4,5,5,4
23,2024-02-01 01:45:00,aurorataylor@example.com,Aurora Taylor,aurorataylor@example.com,Institute U,5,3,4,5,5
24,2024-02-01 02:30:00,jackielee@example.com,Jackie Lee,jackielee@example.com,University V,3,5,5,4,3
26,2024-02-01 04:00:00,isaiahmiller@example.com,Isaiah Miller,isaiahmiller@example.com,Institute X,5,5,4,4,5
27,2024-02-01 04:45:00,stellahall@example.com,Stella Hall,stellahall@example.com,University Y,4,3,5,5,4
28,2024-02-01 05:30:00,calebanderson@example.com,Caleb Anderson,calebanderson@example.com,College Z,5,4,4,5,5
29,2024-02-01 06:15:00,hazelthomas@example.com,Hazel Thomas,hazelthomas@example.com,Institute AA,3,5,5,4,3
30,2024-02-01 07:00:00,dylanmartin@example.com,Dylan Martin,dylanmartin@example.com,University BB,4,4,3,5,4
31,2024-02-01 07:45:00,sophiejohnson@example.com,Sophie Johnson,sophiejohnson@example.com,College CC,5,5,4,5,5

In [39]:
import matplotlib.pyplot as plt
import seaborn as sns

In [40]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


def plot(cols, df):
    # Count occurrences of each feedback
    # feedback_counts = df['feedback'].value_counts().sort_index()
    
    # Use Seaborn's color palette
    colors = sns.color_palette('pastel', len(feedback_counts))
    
    # Create a 2x3 grid of subplots
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    
    # Flatten the axes array for easier iteration
    axes = axes.flatten()
    
    # Plot six pie charts
    for i, ax in enumerate(axes):
        if (i < len(cols)):
            data = df[cols[i]].value_counts().sort_index()
            ax.pie(
                data, 
                labels=data.index, 
                autopct='%1.1f%%', 
                startangle=140, 
                colors=sns.color_palette('pastel', len(data)), 
                wedgeprops={'width': 0.4}, 
                labeldistance=1.1,  # Move labels outward
                pctdistance=0.85   # Move percentages outward
            )
            ax.set_title(f'Feedback Distribution {cols[i]}')
        else: 
            axes[i].axis('off')
    
    # Adjust spacing
    plt.tight_layout()
    
    # Show the plot
    plt.show()

In [41]:
plot(
    [
        "Rate your experience with the overall event", 
        "Rate the activity-1",	
        "Rate the following activity-2",	
        "Rate the following activity-3",	
        "Rate the following activity-4"
    ],
    domain_helpers_only_feedbacks
)

NameError: name 'feedback_counts' is not defined

# Q.2

In [ ]:
domain_leaders =  pd.read_excel('/kaggle/input/hack2skill-assessment-data/Data Management Task.xlsx', sheet_name="Domain Leaders")

In [ ]:
domain_leaders.head()

In [ ]:
domain_leaders_who_responded = pd.merge(
    domain_leaders, 
    feedbacks, 
    how='inner', 
    left_on='Email', 
    right_on='Email Address'
)
domain_leaders_who_responded

In [ ]:
domain_helpers_who_responded = pd.merge(
    domain_helpers, 
    feedbacks, 
    how='inner', 
    left_on='Email', 
    right_on='Email Address'
)
domain_helpers_who_responded

In [ ]:
all_respondees = pd.concat([domain_leaders_who_responded[['Name', 'Email']], domain_helpers_who_responded[['Name', 'Email']]]).drop_duplicates()
all_respondees

In [ ]:
discord_records = pd.read_excel('/kaggle/input/hack2skill-assessment-data/Data Management Task.xlsx', sheet_name="Discord Entries")
discord_records

In [ ]:
respondees_with_discord = pd.merge(
    all_respondees, 
    discord_records, 
    how='inner', 
    left_on='Email', 
    right_on='Email Address'
)
respondees_with_discord[["Name", "Email","Discord Username" ]]

# Q.3

In [ ]:
discord_score = pd.read_excel('/kaggle/input/hack2skill-assessment-data/Data Management Task.xlsx', sheet_name="Best Discord Performer")
discord_score

In [ ]:
all_members = pd.concat([domain_leaders, domain_helpers]).drop_duplicates().reset_index()
all_members

In [ ]:
all_members_with_discord_username = pd.merge(
    all_members, 
    discord_records, 
    how="inner", 
    left_on='Email', 
    right_on='Email Address'
)[['Name', 'Email', 'Discord Username']]

all_members_with_discord_username

In [ ]:
discord_member_details = pd.merge(
    discord_score[['Discord IDs']], 
    all_members_with_discord_username[['Discord Username', 'Email', 'Name']], 
    how="inner", 
    left_on='Discord IDs', 
    right_on='Discord Username'
)[['Name', 'Email']]

discord_member_details

# Q.4

In [ ]:
teacher_responses = pd.read_excel('/kaggle/input/hack2skill-assessment-data/Data Management Task.xlsx', sheet_name="Teacher Details")
teacher_responses

In [ ]:
domain_leaders_email = set(domain_leaders['Email'].unique())
domain_leaders_email

In [ ]:
filtered_teacher_details = teacher_responses[~teacher_responses['Email Address'].isin(domain_helpers_email) & ~teacher_responses['Email Address'].isin(domain_leaders_email)].drop_duplicates()
filtered_teacher_details